### ISSUE TITLE
Vue文件中报错

### ISSUE THREAD

**Issue by Yang2007** [OYsun/vscode-VueHelper#15]
...mapGetters这行报错，
'Property assignment expected.'

怎样能去掉这个报错提示？

**Comment by OYsun** [comment]
这是你书写代码的错误。不是插件的问题，请好好看vuex的文档

**Comment by Yang2007** [comment]
确定不是写错了，可以正常运行，而且代码拷贝到js文件中也不报错，只有在vue文件中报错。
这个问题和插件没关系，只是想请教一下如何去掉错误提示。

**Comment by Yang2007** [comment]
问题已经解决，过来说一下。
vue文件默认是用的html语言，按ctrl+k，m 选择vue语言，报错就没有了。

**Comment by Yang2007** [comment]
但是用vue语言，js提示就没有了。
用html，...mapGetters报错。
