### ISSUE TITLE
Drop syntax definition and split snippets for each languages

### ISSUE THREAD

**Issue by octref** [OYsun/vscode-VueHelper#16]
Hello, I'm working on vetur, and in 0.3.3 I tweaked embedded snippet support.

For the following code, vetur now will mark each region correctly with its embedded language, like this:

```
<template>          // vue
                    // html
</template>         // vue
                    // vue
<style>             // vue
div .test {         // css
  list-style: none; // css
}                   // css
</style>            // vue
```

And snippets will work this way:

- In vue region, vue snippet will be available
- In html region, html snippet will be available
- In css region, css snippet will be available

This applies to all other languages, like scss, stylus, js, ts, etc.

Would you mind

- Suggest users to install vetur and drop the syntax definition in VueHelper. Currently the outdated syntax definition will override vetur's, and it doesn't mark regions and embedded languages correctly. Also I don't want the old syntax definition to be floating around.
- Split snippets into each languages. Now I see you are putting `main.json` [into all languages](https://github.com/OYsun/vscode-VueHelper/blob/dev/package.json#L70-L90). For example, `vue$on` only applies to js or ts, but not css or scss. Once you put that snippet to a separate file, and only define it as a js snippet, it'll only popup in the `<script>` region in vue SFC.

Thanks!

**Comment by OYsun** [comment]
@octref  你好，我有些关于VueHepler和vetur这两个插件的想法希望和你探讨交流，但是在github上并没有找到你的联系方式，如果不介意的话。希望你能告诉我你的联系方式，可以通过邮箱的方式告诉我，我的邮箱 web-oysun@qq.com
