### ISSUE TITLE
0.0.9更新之后，代码高亮和代码提示都没有了

### ISSUE THREAD

**Issue by SaltFish-X** [OYsun/vscode-VueHelper#17]
vscode 1.91
vueHelper 0.0.9
vetur 0.3.6
macOS 10.12.2

代码片段
```vue
<template lang="pug">
  section#driver-team
    z-nav(title="当前隶属车队")
      router-link.button.button-fill.button-form(:to="{ name: 'DriverCar' }") 下一步
</template>

<style lang="stylus">
#driver-team
  .top
    background #fff
    select
      float right

</style>

<script lang="babel">
import Driver from '../services/Driver.js'
export default {
  name: 'driver-team',
  data() {
    return {
      driver: new Driver(),
      teams: [
         {companyName:'', companyAddress:'', contactMobile:'', contactName:'', id:''}
      ]
    }
  },

</script>
```

更新前0.0.9之前<script>部分有高亮和提示，'template'部分有提示和高亮，<style>部分有高亮无提示
更新后，所有部分均失去了提示功能，<script>连高亮都没了

已将vueHelper 、vetur重新卸载并安装。依然没有变化
setting中的配置存在或删除均没有用，之前一直开着这个设置，有高亮有提示
```json
  "files.associations": {
    "*.vue": "vue"
  }
```

新版本下
即使开着js，<script>和'template' 部分均没有提示，之前不开js也是有提示的。

**Comment by OYsun** [comment]
@DreamColl  我这并没有出现你这种情况，目前，js和script是有提示的，在vue文件中的template部分没有提示，是vetur迭代后的问题，我已经提了issues给vetur了

**Comment by OYsun** [comment]
很抱歉自己考虑不周导致你使用的不便，这个问题请看这个issue ： https://github.com/OYsun/vscode-VueHelper/issues/1

**Comment by SaltFish-X** [comment]
谢谢你更新了0.1.0版本
删去
```
  "files.associations": {
    "*.vue": "vue"
  }
```
单独使用vueHelper
template、script、style（style一定在最后）这样的顺序，即可保持template、script的高亮和提示均正常。唯一遗憾的是style，不过可以通过外部引用styuls文件来解决没有提示、高亮和报错的问题。再次感谢

**Comment by nicefan** [comment]
能不能提供一下0.0.7版，升级了后悔死了，Vue文件格式时没有代码提示，html格式时，CSS语法错误，没有高亮。之前0.0.7版好好的！！

**Comment by OYsun** [comment]
@nicefan  兄弟，你看看这个https://github.com/OYsun/vscode-VueHelper/issues/1 。升级到了0.1.0版本不会这样了

**Comment by nicefan** [comment]
唉，0.0.7版的时候两全其美。

2017年2月28日 下午8:54于 OYsun <notifications@github.com>写道：

@nicefan<https://github.com/nicefan> 兄弟，你看看这个#1<https://github.com/OYsun/vscode-VueHelper/issues/1> 。升级到了0.1.0版本不会这样了

―

**Comment by OYsun** [comment]
@nicefan  0.0.7版本fork了vetur的代码高亮功能，这样需要不断的和他同步迭代。不和vetur迭代会引起插件之间冲突。0.1.0版本就不会这样。

**Comment by nicefan** [comment]
可能就是这个原因，fork了，然后我又单独装了，反正是很奇怪

2017年2月28日 下午10:38于 OYsun <notifications@github.com>写道：

@nicefan<https://github.com/nicefan> 0.0.7版本fork了vetur的代码高亮功能，这样需要不断的和他同步迭代。不和vetur迭代会引起插件之间冲突。0.1.0版本就不会这样。

―
