### ISSUE TITLE
这个插件在webstrom里面怎么使用，直接在命令行里npm install vuehelper吗

### ISSUE THREAD

**Issue by shaobeichen** [OYsun/vscode-VueHelper#2]
这个插件在webstrom里面怎么使用，直接在命令行里npm install vuehelper吗，如果有，请说详细一点

**Comment by OYsun** [comment]
这插件是专门适用vscode编辑器的，不同编辑器，IDE的插件不能相互使用吧，我不使用webstrom，对它不了解，你可以查阅相关资料试试。另外这个插件我没有发布在npm，是发布在vscode扩展市场上`npm install vuehelper`是无效的
