### ISSUE TITLE
希望支持Emmet语法

### ISSUE THREAD

**Issue by DCjanus** [OYsun/vscode-VueHelper#25]
QAQ VScode似乎已经原生支持HTML文件中使用Emmet语法，用习惯后在.vue下无法使用，很是难受

**Comment by ghost** [comment]
这个问题早就支持  setting.json 添加

,"emmet.useNewEmmet": false,
    "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html"
    },
