### ISSUE TITLE
template里面的html代码高亮问题

### ISSUE THREAD

**Issue by WangYang-Rex** [OYsun/vscode-VueHelper#3]
![image](https://cloud.githubusercontent.com/assets/7553998/21488983/d0605a9a-cc20-11e6-9a9a-8b2e46470571.png)

**Comment by OYsun** [comment]
我这并没有出现类似的情况，另外，你这张图并没有显示出什么问题，第18行出现代码高亮问题我觉得是你那里语法错误，比如粗心忘记闭合标签，缺少个别符号等等。
