### ISSUE TITLE
如何配置html,css代码提示和代码格式化

### ISSUE THREAD

**Issue by featherfly** [OYsun/vscode-VueHelper#7]
把编辑器从html切换到vue编辑器，html、css的代码提示就没了
代码格式化也没了

**Comment by OYsun** [comment]
见 https://github.com/OYsun/vscode-VueHelper/issues/1

**Comment by featherfly** [comment]
看了下，就是用html编辑器打开？用html编辑器打开vuehelper的代码提示就没了
