### ISSUE TITLE
script标签里面不出提示

### ISSUE THREAD

**Issue by zjhr** [OYsun/vscode-VueHelper#9]
目前发现在.vue文件里面的script标签，输入代码，不出现提示，除了script标签以外，其他地方都可以提示

**Comment by zjhr** [comment]
不知道是否和别的插件冲突了

**Comment by OYsun** [comment]
vscode打开速度非常快是因为它加载文件是按需加载，最近的新版本对这方面做的有点变态了，你这个问题其实你只要随便打开一个js文件，再回去看.vue文件后在script标签就有代码提示了，你可以试试。我实验了了一下，一开始启动vscode的时候，你没有打开任何js文件，那么html和.vue文件都没有js代码提示，但是只要你打开了js文件，就不会出现这个问题，可能是vscode默认启动不会加载js相关功能配置来提高打开速度，只有你打开了js文件才会加载有关于js的相关插件和功能。

**Comment by zjhr** [comment]
果然。。。。

**Comment by yanghdx** [comment]
我这边情况是： .vue里面console.x这样代码都有提示， 类似import X from '../../../libs/x'  这样的代码，首先不能定位文件，其次当输入 X. 的时候 也没有方法提示。是vsc本身不支持，还是我个人设置问题？

**Comment by OYsun** [comment]
@yanghdx  定位文件需要这个[ Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) 插件，`console`这些原生javascript的方法本身vscode就会提示，外部文件export出来的方法和属性，需要import进来才会有提示。

**Comment by yanghdx** [comment]
@OYsun 谢谢，.vue文件 import进来的没提示 这个应该怎么解决？

**Comment by OYsun** [comment]
@yanghdx 见https://github.com/OYsun/vscode-VueHelper/issues/1 ，你是不是设置了
```javascript
 "files.associations": {
        "*.vue": "vue"
     }
```
试一试去掉这个设置
